(ns mailcrunch.backend.db
  (:use     [korma.db :only [defdb postgres]])
  (:require [korma.core :as kc]))

(defdb prod (postgres {:db "mailcrunch"
                       :user "mailcrunch"
                       :password "n1c013tt0."
                       :delimiters ""}))


(defmacro q-number-of [table-ref & query]
  `(let [basetmp# (-> (kc/select* ~table-ref)
                      (kc/aggregate (~'count :*) :count))]
    (if ~query
       (-> basetmp#
            (kc/where (first ~@query)))
      basetmp#)))

(defmacro q-get [table-ref & query]
  `(let [basetmp# (kc/select* ~table-ref)]
     (cond-> basetmp#
             (not (empty? ~query)) (kc/where (first ~@query)))))

(defn new-userdef-seq-val [entity]
	(let [seq-name (-> (:table entity)
										 (str "_userdef"))
				query (str "select nextval('public." seq-name "'::text)")]
		(println query)
		(kc/exec-raw query :results)
		))


(def insert-fns {
								 :set-userdef-id (fn [values]
		 																(let [seq-name (-> 	(:table entity)
					 																							(str "_userdef"))
					 																query    (str "select nextval('public." seq-name "'::text)")
					 																curr_userdef-id (:userdef_id values)]
					 														(if (nil? curr_userdef-id)
							 													(let [[{:keys [nextval]}]	 (kc/exec-raw query :results)]
																						(assoc values :userdef_id nextval))
							 													values)))
								 :set-creation-date (fn [values] {:b 2})
								 :set-created-by (fn [values]{:a 3})
								 })


;I need to pass the entity to v# therefore the following doesn't work.
(defmacro insert-triggers 
	"For every insert make sure we add all the mandatory fields which can be autogenerated (i.e. userdef_id, creation_date, etc..)"
	[entity]
		;(merge m (reduce #(%2 %1) m (vals fns)))
	 `(for [[k# v#] ~insert-fns] 
			(prepare ~entity v#)))
